### ISSUE TITLE
404 template is broken

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Reach#35]
Example: http://demo.wpcharitable.com/reach/232/

**Comment by RCMainak** [comment]
Seems like the width in the banner class is causing the problem. Removing it will solve the problem, but not sure if that will break something else or not.

**Comment by RCMainak** [comment]
@ericnicolaas as you mentioned in #36 are you still looking for contributors to make appropriate changes without modifying the existing css styles?

**Comment by ericnicolaas** [comment]
@RCMainak Yep, would love to have a fix contributed. As I mentioned in the comment on #36, this should be fixable by updating `404.php`.

Cheers,
Eric

**Comment by ericnicolaas** [comment]
Closed in c70403b7b6801d251bfd670c889043867839cd3e
