### ISSUE TITLE
Donation form is too wide on campaign page

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Reach#37]
When you have the donation form set to display on the campaign page, it is wider than the container it is in.

<img width="1088" alt="screenshot 2016-10-08 15 57 44" src="https://cloud.githubusercontent.com/assets/676582/19210952/0157652a-8d70-11e6-9303-4c859f85ef88.png">

**Comment by BhaveshSGupta** [comment]
@ericnicolaas  can I have any link to particular page because i cant find it on demo site
