### ISSUE TITLE
Mobile menu icon is positioned off screen if no social icons are active

### ISSUE THREAD

**Issue by epstarr** [Charitable/Reach#45]

**Comment by epstarr** [comment]
Had to set the following CSS to have the menu icon be displayed:

`.layout-wide .site-navigation {
    top: -23px;
    top: -2.3rem;
}`

**Comment by ericnicolaas** [comment]
Thanks @epstarr. I'll make sure we fix this in the next release.

**Comment by Himani3010** [comment]
@ericnicolaas I ain't able to reproduce this issue. In my test environment, the mobile menu icon is displayed when no social icons are active. 

I came across another issue i,e, social icons and menu icon aren't aligned properly. Please find the screenshot below for reference:
![image](https://user-images.githubusercontent.com/22770041/50347966-797f6400-055d-11e9-8051-29e8d29d155c.png)

**Comment by Himani3010** [comment]
@ericnicolaas Please find the respective PR here: https://github.com/Charitable/Reach/pull/68

**Comment by ericnicolaas** [comment]
Re-opening.

**Comment by ericnicolaas** [comment]
Closed by 48f90bbc9f0d9dd21d3d933400409430452f819d
