### ISSUE TITLE
Support no user dashboard menu set

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Reach#52]
If you don't set a user dashboard menu, every page appears with the Dashboard header.

**Comment by ericnicolaas** [comment]
@Himani3010 I'm having a hard time reproducing this issue now. Do you recall if you were able to reproduce the issue, and if so, what your setup was? i.e. Was it a brand new site?

**Comment by Himani3010** [comment]
@ericnicolaas I was able to reproduce this issue in my test environment. Please see the steps mentioned below:
(Skip the 1st step if you have the Donations Table page in User Dashboard Menu)
1. Create a User Dashboard Menu including Donations Table page 
2. UnCheck Display Location to User Dashboard if checked
3. The text **Dashboard** is displayed on the Donations page header whereas it should be the page header i.e,`Donations Table` as User Dashboard location is unchecked

Please, let me know if this makes sense!

**Comment by ericnicolaas** [comment]
Thanks @Himani3010. I was able to reproduce it with those instructions. 

I just reviewed your PR and made a couple small adjustments, but merged it in now. So this is now closed with https://github.com/Charitable/Charitable/commit/1469620a7f27df5628dadf722bba15a0c5a39204
