### ISSUE TITLE
.shadow-wrapper div breaks alignment of campaign stats

### ISSUE THREAD

**Issue by epstarr** [Charitable/Reach#59]
http://demo.wpcharitable.com/reach/campaigns/wateraid-clean-water-for-remote-communities/

Showing up on my theme pages as well now. I removed the .shadow-wrapper div from the \reach\charitable\campaign\summary.php file. What is the purpose of this div?

**Comment by ericnicolaas** [comment]
@epstarr Thanks for reporting this; we'll make sure this gets fixed.

The `.shadow-wrapper` div is used in the Fixed layout; in the Wide layout it should just be full-width, but we need to fix that obviously. :)

**Comment by ericnicolaas** [comment]
This was actually fixed back in 7dcc5e935c659984e13b922682c0d4beeba8cfde but that hasn't been pushed to the theme yet.
