### ISSUE TITLE
2 menus overlapping

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Reach#79]
bug report: in Reach on my mobile, there are 2 menus that overlap: A) profile menu B) site menu. It is impossible to select the site menu this way. See screenshots below, one is on firefox mobile (on Android Pie) and one on Chrome mobile (als Android Pie). 

Chrome:

![Screenshot_20200702-135706_Browser](https://user-images.githubusercontent.com/42555414/86357898-dc7faa00-bc6e-11ea-9dd8-f06eb85e218d.png)

Firefox: 

![Screenshot_20200702-135835_IceCatMobile](https://user-images.githubusercontent.com/42555414/86357902-ddb0d700-bc6e-11ea-8693-efc387b71823.png)

**Comment by ericnicolaas** [comment]
@Rik44444 This isn't something we'll solve at the Reach level, since it would only apply to logged in users with the admin bar, but it can be fixed with this plugin:

https://wordpress.org/plugins/admin-bar-wrap-fix/
