### ISSUE TITLE
Block Editor: Akward margins with Column blocks

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Reach#81]
Dear Eric,
a bug report about a few layout issues when using Gutenberg columns in the Reach Theme. See screenshots and https://testtest.future.ngo/faq/en

It seems there are a few issues:
1. the margins below a column seem too large
2. this appears to be especially the case when the content of the colums is a quote or a pullquote
3. in the left column, text breaks off in several sections when there is a pullquote on the right

1st screenshot:
![Annotation 2020-07-31 183449](https://user-images.githubusercontent.com/42555414/89057097-5b92fb80-d35d-11ea-8c8b-0da9932dc56b.png)

2nd screenshot:
![Annotation 2020-07-31 183533](https://user-images.githubusercontent.com/42555414/89057102-5d5cbf00-d35d-11ea-8f10-7bc539ee32ce.png)

3rd screenshot:
![Annotation 2020-07-31 183648](https://user-images.githubusercontent.com/42555414/89057103-5df55580-d35d-11ea-95da-a297859970af.png)

**Comment by ericnicolaas** [comment]
The following CSS helped here:

```
.entry-block .wp-block-quote {
  left: 0;
  width: 100%;
  padding-top: 0;
  padding-bottom: 0;
}
.wp-block-columns {
  margin-bottom: 0;
}
```

Though the `.wp-block-columns` styling is probably not idea.

**Comment by Rik44444** [comment]
great thanks this worked for me also
