### ISSUE TITLE
buttons are not displayed in theme colours

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Reach#82]
when adding buttons to a page  in the default colour, using the Gutenberg Wordpress editor, these are not displayed in the Theme's colour (as adjustable in "Customize") but in a sort of dark grey. 
Request: 
1. to make the default colour of buttons align with the theme colours
2. advice on a temporary work-around for this, until it is fixed in Reach, e.g. custom CSS code to make buttons the theme-colours

![reach](https://user-images.githubusercontent.com/42555414/89124128-d03c7600-d4d4-11ea-9c82-7903a7bbc9e0.png)

![reach2](https://user-images.githubusercontent.com/42555414/89124409-0da20300-d4d7-11ea-9588-03ea1c9d03ab.png)

**Comment by ericnicolaas** [comment]
Hey @Rik44444, the temporary workaround would be to add some custom styles (probably using the [`wp_head` hook](https://developer.wordpress.org/reference/hooks/wp_head/)) and to pick up the accent colour in that. This will get you the HEX code for the colour:

```
$colour = esc_attr( reach_get_theme()->get_theme_setting( 'accent_colour' ) );
```

Longer term, Reach should define its own colour palette which will work for buttons and any other blocks that use the colour picker. I will make a separate issue for that.

**Comment by ericnicolaas** [comment]
Closing in favour of #84
