### ISSUE TITLE
Making it possible in "Customise" to change background colour

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Reach#83]
At the moment it is not possible in "Customise" to change background colour. 
Request: 
1. to make this possible
2. advice on a temporary work-around, as additional CSS

![reach3](https://user-images.githubusercontent.com/42555414/89124453-5d80ca00-d4d7-11ea-9f3d-853b146e82db.png)

**Comment by ericnicolaas** [comment]
I'm not sure we will add this as a theme option, but the workaround is pretty straightforward:

```
#main, 
#header {
  background-color: #fff;
}
```
