### ISSUE TITLE
make headings for comments and anonymous donating on donation form

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Reach#85]
feature request to make headings for the 'comments' and 'anononymous donating' sections on the donation form, in the same format as the headings for 'Your donation', 'Details' and 'Terms and conditions'

![ff](https://user-images.githubusercontent.com/42555414/93575500-0311cf00-f99a-11ea-8370-809dfdd755f9.png)

**Comment by Rik44444** [comment]
ì found [this snippet](https://github.com/Charitable/library/blob/master/donation-form/change-section-headers.php), which could work as a workaround I think. Can you help with how to add the headings for the Comments and Anonymous donation section using this snippet as a workaround?

**Comment by Rik44444** [comment]
**workaround:** 

The Anonymous Donation checkbox and the comment field are both in the 'meta' section of the donation form. You can add headers and descriptive text there using the 'charitable_donation_form_meta_fields' filter, as per the example at https://github.com/Charitable/library/blob/master/forms/general/add-description-field.php#L38
 
On the highlighted line, replace 'charitable_campaign_submission_campaign_fields' with 'charitable_donation_form_meta_fields'. Then you can add each of your fields there, with the fragment of text being a field with a 'type' of 'paragraph'. For a header, you would set 'type' to 'content' and add an array element of 'content' with the HTML header. i.e.
 
$fields['comment_header_field'] = array(
'type' => 'content',
'priority' => 3,
'content' => '<h3>Comment</h3>'
);
 
---------------------------	
	
/**
 * https://github.com/Charitable/library/blob/master/forms/general/add-description-field.php#L38
 * 
 * This example shows how to add a block of text to a form. 
 *
 * Most of the forms that are used on the frontend in Charitable
 * include filters to allow you to add extra fields. You can adapt
 * the example below to work with another form by switching the hook
 * that is used:
 *
 * - Registration form: charitable_user_registration_fields
 * - Profile form (user section): charitable_user_fields
 * - Profile form (address section): charitable_user_address_fields
 * - Profile form (social section): charitable_user_social_fields
 * - Donation form (user section): charitable_donation_form_user_fields
 * - Donation form (donation amount section): charitable_donation_form_donation_fields
 * - Campaign form (campaign section): charitable_campaign_submission_campaign_fields
 * - Campaign form (donation options section): charitable_campaign_submission_donation_options_fields
 * - Campaign form (user section): charitable_campaign_submission_user_fields
 * 
 * The example below adds a field to the campaign creation form 
 * in Charitable Ambassadors.
 */

function ed_add_description_field_to_form2( $fields ) {

    $fields[ 'heading_comments' ] = array(
        'type'          => 'content',
        'priority'      => 3, 
        'fullwidth'     => true, 
      	'content'       => '<h4>Leave a comment</h4>'
    );

    $fields[ 'heading_data_use' ] = array(
        'type'          => 'content',
        'priority'      => 7, 
        'fullwidth'     => true, 
      	'content'       => '<h4>How we use your data</h4>'
    );

    return $fields;

}

add_filter( 'charitable_donation_form_meta_fields', 'ed_add_description_field_to_form2' );

**Comment by ericnicolaas** [comment]
@Rik44444 Thanks for posting your workaround for this. The Donor Comments & Anonymous Donations fields are both set up to show in the 'meta' section as you found, which doesn't show with a header. At this stage that's not something we're planning to change, though we are looking at a refresh of the donation form design in Charitable which may touch on this. For now I'm going to close this issue here.
