### ISSUE TITLE
feature request: Social sharing buttons on receipts

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Reach#87]
Hi, Charitable has great social sharing buttons on the Campaign pages, it would be great if these could be extended to the Donation Receipt, both in the browser and the email, with an automatic suggestion for content like "I just donated {{amount}} to {{campaign}} via {{name+hyperlink URL to site}}"

**Comment by ericnicolaas** [comment]
@Rik44444 This is something we want to solve at the Charitable level, not just for Reach. I'm closing this issue here but it's definitely on our radar for future Charitable development.
