### ISSUE TITLE
Sharing: Twitter sharing does not pre-fill tweet with text & URL

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Reach#88]
Possible bug: when sharing campaign pages with the social share buttons to FB and Linkedin, you are led to a FB or Linkedin post message, with a link to the campaign site already in there. However, with Twitter, I do not get such a link. A new window opens, with my Twitter homepage, but that's it: no suggestion for a message and no automatic link to the campaign page

**Comment by ericnicolaas** [comment]
@Rik44444 I've been able to reproduce this. It looks like Twitter have made this more difficult and it now requires loading a script to have it work correctly. 

https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/web-intent
