### ISSUE TITLE
feature request: being able to manually set the size of the images on the campaign pages

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Reach#98]
feature request: being able to manually set the size of the images on the campaign pages, they are currently much too big

**Comment by ericnicolaas** [comment]
This isn't a setting we're planning to add, but it's possible to tweak the size of the campaign images with a combination of CSS and by overriding the `charitable/campaign/featured-image.php` template in Reach to use a different sized image.
 
https://developer.wordpress.org/reference/functions/get_the_post_thumbnail/

The second argument for `get_the_post_thumbnail` specifies the image size, and it can accept an array of numbers so you can specify the width & height.

**Comment by ericnicolaas** [comment]
Following on from the previous message, here's a bit of sample CSS that will force a fixed width on the image:

```
.campaign-summary .campaign-image img {
  max-width: 50rem;
}
@media screen and (min-width:50em) {
  .campaign-summary .campaign-details, .campaign-summary .campaign-sharing {
    max-width: 100%;
    width: calc(100% - 50rem);
    float: right;
  }

  .campaign-summary .campaign-video, .campaign-summary .campaign-image {
    width: 50rem;
  }
}
```

Note that this is required in combination with overriding the thumbnail image as mentioned in the previous comment. 

Also, this example sets a fixed width of 50rem, equals 500px, so if you want bigger images, adjust it up; for smaller images, adjust it down. 1rem = 10px.
